---
- name: Edit DNS
  hosts: all
  strategy: free
  become: true
  gather_facts: false
  tasks:
      - name: Add IP of DNS server
        lineinfile:
          path: /etc/resolv.conf
          regexp: '^nameserver'
          line: 'nameserver 10.0.0.108'

      - name: Add search of DNS server
        lineinfile:
          path: /etc/resolv.conf
          regexp: '^search'
          line: 'search rke2.internal'
